title: Chelsea Yueh
#logo: 
description: Data Analytics and BI Professional with a Master’s in Information Systems and hands-on experience. Skilled in SQL, Python, Power BI, Tableau.
#show_downloads:
theme: jekyll-theme-slate

